language: node_js
node_js:
- "node"
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
  # Updating NPM to relevant version >= 3 on Node.JS LTS
- npm i -g npm@^3
- npm i -g brfs
script:
- npm run lint
- npm run test
sudo: false
addons:
  apt:
    packages:
    - sshpass
    - google-chrome-stable